apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: disk01
  labels:
    app: mysql
spec:
  storageClassName: nfs-policy
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
