apiVersion: apps/v1
kind: Deployment
metadata:
 name: frontend
spec:
 replicas: 3
 selector:
   matchLabels:
     app: front
 template:
   metadata:
     labels:
       app: front
   spec:
     containers:
     - name: web
       #       image: emeirell/apache:php7
       image: demo.goharbor.io/emeirelles/apache:latest
       imagePullPolicy: IfNotPresent
       ports:
       - containerPort: 80
